Feature/junit testing
wolox-training/jmo-java pull request #11
Opened 2020-09-25 13:56 UTC by JJhoan

## Summary

-Added test for controllers, repositories and domains 

## Trello card

https://trello.com/c/UnUcZbof/28-junit-testing

2020-09-30 14:08 UTC, jeymarsonwolox requested changes

2020-09-30 14:08 UTC, jeymarsonwolox commented on src/test/java/com/wolox/training/controllers/BookControllerTest.java
> +            .characterEncoding("utf-8"))
extract `utf-8` to a constants

2020-09-30 14:08 UTC, jeymarsonwolox commented on src/test/java/com/wolox/training/controllers/BookControllerTest.java
> +                    + "    \"isbn\" : \"6453723453\"\n"
you repeat this json, extract this

2020-09-30 14:08 UTC, jeymarsonwolox commented on src/test/java/com/wolox/training/controllers/UserControllerTest.java
> +                    + "}"
you repeat this json, extract this

2020-10-01 21:22 UTC, jeymarsonwolox submitted a review, later dismissed

2020-10-02 21:01 UTC, jeymarsonwolox approved these changes

2020-10-05 18:36 UTC, IgnOliveto approved these changes

2020-10-05 20:31 UTC, merged