Added spring security to the app
wolox-training/jmo-java pull request #12
Opened 2020-09-25 19:45 UTC by JJhoan

## Summary
- Added spring security
- Configuration is added to not request authorization to the creation methods
## Trello card
https://trello.com/c/SQbhj9mI/23-integrar-spring-security

2020-09-30 14:13 UTC, jeymarsonwolox requested changes
what happened to your tab?

2020-09-30 14:13 UTC, jeymarsonwolox commented on src/main/java/com/wolox/training/model/User.java
> +        checkNotNull(password, "Password are not  should nulls");
check empty password to

2020-09-30 14:13 UTC, jeymarsonwolox commented on src/main/java/com/wolox/training/security/SecurityConfig.java
> +@ComponentScan("com.wolox.training.security")
you don't need this

2020-10-01 21:24 UTC, jeymarsonwolox submitted a review, later dismissed

2020-10-09 14:37 UTC, IgnOliveto approved these changes

2020-10-09 15:37 UTC, jeymarsonwolox approved these changes

2020-10-09 18:41 UTC, merged