Feature/external appi
wolox-training/jmo-java pull request #13
Opened 2020-09-30 21:29 UTC by JJhoan

## Summary
-Added method to search isbn from an external api

## Trello card
https://trello.com/c/eABUqrOZ/22-integraci%C3%B3n-api-externa

2020-10-01 21:25 UTC, jeymarsonwolox requested changes
why this branch points to master?

2020-10-02 21:03 UTC, jeymarsonwolox requested changes

2020-10-02 21:03 UTC, jeymarsonwolox commented on src/main/java/com/wolox/training/controllers/UserController.java
> +    public UserController(@Lazy PasswordEncoder passwordEncoder) {
remove `@Lazy`, add `@Autowired` and mock bean in tests

2020-10-09 15:43 UTC, jeymarsonwolox submitted a review, later dismissed

2020-10-14 17:20 UTC, IgnOliveto approved these changes

2020-10-14 18:48 UTC, jeymarsonwolox approved these changes

2020-10-14 19:15 UTC, merged