Feature/creation book model
wolox-training/jmo-java pull request #3
Opened 2020-09-16 21:10 UTC by JJhoan

## Summary
- The book entity is added
- Added pattern builder
- Added guava and lombok dependences
## Trello Card
https://trello.com/c/3LGtTLWM/14-crear-modelo-de-book

2020-09-18 15:01 UTC, jeymarsonwolox requested changes
Hi @JJhoan , do you think if for this card we also remove the part of the Builder pattern, we can see it later. I think it's very good that you handle it, that will make it easier for you to work when you enter a project. For now let's leave the class in a basic way, as indicated in the card.

2020-09-18 15:46 UTC, jeymarsonwolox requested changes

2020-09-18 15:46 UTC, jeymarsonwolox commented on src/main/java/com/wolox/training/model/Book.java
> +    Long idBook;
Add`@GeneratedValue(strategy = GenerationType.SEQUENCE)`, to automatically generate the id value.
by convection we define the attributes with the following order
`@Id`
`@GeneratedValue(strategy = GenerationType.SEQUENCE)`
`private Long idBook`

2020-09-18 15:46 UTC, jeymarsonwolox commented on src/main/java/com/wolox/training/model/Book.java
> +    private @Column
`@Column is not necesary`

2020-09-18 15:46 UTC, jeymarsonwolox commented on src/main/java/com/wolox/training/model/Book.java
> +    private @Column(nullable = false)
Let's use `@NotNull` instead of `@Column (nullable = false)`.
`@NotNull` checks that the property is not null before going to the database.

2020-09-18 15:46 UTC, jeymarsonwolox commented on src/main/java/com/wolox/training/model/Book.java
> +    public void setIdBook(Long idBook) {
Remove this method, JPA takes care of giving the values to the id.
We don't want that the id of an object can be changed, that the only one that can modify it is JPA.

2020-09-18 19:02 UTC, jeymarsonwolox requested changes

2020-09-18 19:02 UTC, jeymarsonwolox commented on src/main/java/com/wolox/training/model/Book.java
> +import com.sun.istack.NotNull;
import `@NotNull` from `javax.validation.constraints.NotNull`

2020-09-18 19:02 UTC, jeymarsonwolox commented on src/main/java/com/wolox/training/model/Book.java
> +import com.sun.istack.Nullable;
this is not necesary

2020-09-18 19:02 UTC, jeymarsonwolox commented on src/main/java/com/wolox/training/model/Book.java
> +    @Nullable
this is not necesary

2020-09-18 19:54 UTC, jeymarsonwolox approved these changes

2020-09-21 17:00 UTC, IgnOliveto approved these changes

2020-09-21 17:06 UTC, merged