Added Book repository
wolox-training/jmo-java pull request #4
Opened 2020-09-17 14:48 UTC by JJhoan

## Summary
-Added Book repository
-Added method to search book by author

## Trello Card
https://trello.com/c/WMEndMPS/15-crear-un-repositorio-de-books

2020-09-17 16:07 UTC, jeymarsonwolox requested changes

2020-09-17 16:07 UTC, jeymarsonwolox commented on src/main/java/com/wolox/training/repositories/BookRepository.java
> +    Book findBookByAuthor(@Param("author") String author);
`@Query` is not necesary, the orm takes care of that.
You only need `Optional<Book> findByAuthor(String author)`.
If you want ignore uppercas use `Optional<Book> findByAuthorIgnoreCase(String author)`

2020-09-18 15:05 UTC, jeymarsonwolox requested changes

2020-09-18 15:05 UTC, jeymarsonwolox commented on src/main/java/com/wolox/training/repositories/BookRepository.java
> +    Book findByAuthor(@Param("author") String author);
I recommend the use of Optional to avoid future null checks `Optional<Book>`, you can read more here https://www.baeldung.com/java-optional

2020-09-18 19:55 UTC, jeymarsonwolox requested changes

2020-09-18 19:55 UTC, jeymarsonwolox commented on src/main/java/com/wolox/training/repositories/BookRepository.java
> +    Optional<Book> findByAuthor(@Param("author") String author);
`@Param("author")` is not necesary

2020-09-18 19:56 UTC, jeymarsonwolox requested changes

2020-09-18 19:56 UTC, jeymarsonwolox commented on src/main/java/com/wolox/training/repositories/BookRepository.java
> +public interface BookRepository extends CrudRepository<Book, Long> {
add `@Repository`

2020-09-18 21:03 UTC, jeymarsonwolox submitted a review, later dismissed
Great!!

2020-09-21 16:59 UTC, IgnOliveto approved these changes, later dismissed

2020-09-21 17:46 UTC, jeymarsonwolox approved these changes

2020-09-22 15:21 UTC, IgnOliveto approved these changes

2020-09-23 15:52 UTC, merged