Create user model and relation one to many with book
wolox-training/jmo-java pull request #6
Opened 2020-09-18 14:58 UTC by JJhoan

## Summary
-Added user entity
-One to many  relationship was created
-Added methods to add and delete books in user entity

## Trello Card
https://trello.com/c/8lZeztLA/19-crear-modelo-de-user

2020-09-23 16:06 UTC, IgnOliveto commented on src/main/java/com/wolox/training/model/User.java
> +@Entity(name = "Usser")
I think the name of the table is wrong.

2020-09-23 16:06 UTC, IgnOliveto commented on src/main/java/com/wolox/training/model/User.java
> +    @JoinColumn(name= "user_id")
You would have to define the type of the relationship and type of cascade

2020-09-23 16:16 UTC, jeymarsonwolox approved these changes

2020-09-23 16:16 UTC, jeymarsonwolox commented on src/main/java/com/wolox/training/model/Book.java
> +    private User user;
you don't need the `@JoinColum` annotation

2020-09-23 16:16 UTC, jeymarsonwolox commented on src/main/java/com/wolox/training/model/User.java
> +    @JoinColumn(name= "user_id")
you don't need de `@JoinColum` annotation for this

2020-09-23 16:32 UTC, jeymarsonwolox requested changes

2020-09-23 16:32 UTC, jeymarsonwolox commented on src/main/java/com/wolox/training/model/Book.java
> +    @JoinColumn(name = "user_id")
use `@ManyToMany`, one user can be associated with many books and one book can be associated with many users

2020-09-23 16:32 UTC, jeymarsonwolox commented on src/main/java/com/wolox/training/model/User.java
> +    @OneToMany
use `@ManyToMany`, one user can be associated with many books and one book can be associated with many users

2020-09-23 20:56 UTC, jeymarsonwolox requested changes

2020-09-23 20:56 UTC, jeymarsonwolox commented on src/main/java/com/wolox/training/model/Book.java
> +    private List<User> users;
add `@JsonIgnore` to avoid a cyclic reference when querying

2020-09-25 16:42 UTC, jeymarsonwolox commented on src/main/java/com/wolox/training/model/Book.java
> +    private List<User> users;
@JJhoan  make this please

2020-09-28 14:09 UTC, jeymarsonwolox submitted a review, later dismissed

2020-09-28 15:17 UTC, IgnOliveto approved these changes, later dismissed

2020-09-28 22:29 UTC, jeymarsonwolox approved these changes

2020-09-29 15:38 UTC, IgnOliveto submitted a review, later dismissed

2020-09-29 16:39 UTC, IgnOliveto approved these changes

2020-09-29 21:58 UTC, merged