Creation of CRUD for users and operations for add and remove books
wolox-training/jmo-java pull request #9
Opened 2020-09-18 20:28 UTC by JJhoan

## Summary
-Added Crud to user
-Added methods for add and remove books

##Trello Card
https://trello.com/c/gbgKcodC/21-crear-user-controller-con-las-operaciones-crud-de-user

2020-09-23 20:54 UTC, jeymarsonwolox requested changes

2020-09-23 20:54 UTC, jeymarsonwolox commented on src/main/java/com/wolox/training/controllers/UserController.java
> +    public static final String REMOVE_BOOK = "/removeBook/{idUser}/{idBook}";
you can extract all routes (books and users) in one file

2020-09-23 20:54 UTC, jeymarsonwolox commented on src/main/java/com/wolox/training/controllers/UserController.java
> +            throw new UserNotFoundException("User not found");
you repeat `User not found` extract to a constants

2020-09-23 20:54 UTC, jeymarsonwolox commented on src/main/java/com/wolox/training/controllers/UserController.java
> +        Book book = bookRepository.findById(idBook).orElseThrow(() -> new BookNotFoundException("Book not found"));
extract `Book not found` to a constants

2020-09-28 14:11 UTC, jeymarsonwolox approved these changes, later dismissed
Excellent!!

2020-09-29 16:41 UTC, jeymarsonwolox approved these changes, later dismissed

2020-10-01 21:09 UTC, jeymarsonwolox approved these changes, later dismissed

2020-10-02 18:29 UTC, IgnOliveto commented on src/main/java/com/wolox/training/constants/Message.java
> +    public static final String BOOK_CAN_BE_NULL = "Book can not be null";
The enum here should be "BOOK_CANT_BE_NULL"

2020-10-02 18:38 UTC, IgnOliveto approved these changes

2020-10-02 18:39 UTC, jeymarsonwolox approved these changes

2020-10-02 18:43 UTC, merged